// Code generated by gen-property-names.py DO NOT EDIT.
package api

import "fmt"

// FormFillActionKey represents valid keys for FormFillAction.value
type FormFillActionKey string

// Valid FormFillActionKey values
const (
	FormFillActionValueKeyTitle           FormFillActionKey = "title"
	FormFillActionValueKeyFirstName       FormFillActionKey = "first_name"
	FormFillActionValueKeyMiddleName      FormFillActionKey = "middle_name"
	FormFillActionValueKeyLastName        FormFillActionKey = "last_name"
	FormFillActionValueKeyFullName        FormFillActionKey = "full_name"
	FormFillActionValueKeyEmail           FormFillActionKey = "email"
	FormFillActionValueKeyCompany         FormFillActionKey = "company"
	FormFillActionValueKeyAddress1        FormFillActionKey = "address1"
	FormFillActionValueKeyAddress2        FormFillActionKey = "address2"
	FormFillActionValueKeyAddress3        FormFillActionKey = "address3"
	FormFillActionValueKeyCity            FormFillActionKey = "city"
	FormFillActionValueKeyState           FormFillActionKey = "state"
	FormFillActionValueKeyPostalCode      FormFillActionKey = "postal_code"
	FormFillActionValueKeyCountry         FormFillActionKey = "country"
	FormFillActionValueKeyPhone           FormFillActionKey = "phone"
	FormFillActionValueKeyCcName          FormFillActionKey = "cc_name"
	FormFillActionValueKeyCcNumber        FormFillActionKey = "cc_number"
	FormFillActionValueKeyCcExpMonth      FormFillActionKey = "cc_exp_month"
	FormFillActionValueKeyCcExpYear       FormFillActionKey = "cc_exp_year"
	FormFillActionValueKeyCcExp           FormFillActionKey = "cc_exp"
	FormFillActionValueKeyCcCvv           FormFillActionKey = "cc_cvv"
	FormFillActionValueKeyUsername        FormFillActionKey = "username"
	FormFillActionValueKeyPassword        FormFillActionKey = "password"
	FormFillActionValueKeyCurrentPassword FormFillActionKey = "current_password"
	FormFillActionValueKeyNewPassword     FormFillActionKey = "new_password"
	FormFillActionValueKeyTotp            FormFillActionKey = "totp"
)

// validFormFillActionKeys is the set of all valid FormFillActionKey values
var validFormFillActionKeys = map[FormFillActionKey]bool{
	FormFillActionValueKeyTitle:           true,
	FormFillActionValueKeyFirstName:       true,
	FormFillActionValueKeyMiddleName:      true,
	FormFillActionValueKeyLastName:        true,
	FormFillActionValueKeyFullName:        true,
	FormFillActionValueKeyEmail:           true,
	FormFillActionValueKeyCompany:         true,
	FormFillActionValueKeyAddress1:        true,
	FormFillActionValueKeyAddress2:        true,
	FormFillActionValueKeyAddress3:        true,
	FormFillActionValueKeyCity:            true,
	FormFillActionValueKeyState:           true,
	FormFillActionValueKeyPostalCode:      true,
	FormFillActionValueKeyCountry:         true,
	FormFillActionValueKeyPhone:           true,
	FormFillActionValueKeyCcName:          true,
	FormFillActionValueKeyCcNumber:        true,
	FormFillActionValueKeyCcExpMonth:      true,
	FormFillActionValueKeyCcExpYear:       true,
	FormFillActionValueKeyCcExp:           true,
	FormFillActionValueKeyCcCvv:           true,
	FormFillActionValueKeyUsername:        true,
	FormFillActionValueKeyPassword:        true,
	FormFillActionValueKeyCurrentPassword: true,
	FormFillActionValueKeyNewPassword:     true,
	FormFillActionValueKeyTotp:            true,
}

// AllFormFillActionKeys returns all valid FormFillActionKey values
var AllFormFillActionKeys = []FormFillActionKey{
	FormFillActionValueKeyTitle,
	FormFillActionValueKeyFirstName,
	FormFillActionValueKeyMiddleName,
	FormFillActionValueKeyLastName,
	FormFillActionValueKeyFullName,
	FormFillActionValueKeyEmail,
	FormFillActionValueKeyCompany,
	FormFillActionValueKeyAddress1,
	FormFillActionValueKeyAddress2,
	FormFillActionValueKeyAddress3,
	FormFillActionValueKeyCity,
	FormFillActionValueKeyState,
	FormFillActionValueKeyPostalCode,
	FormFillActionValueKeyCountry,
	FormFillActionValueKeyPhone,
	FormFillActionValueKeyCcName,
	FormFillActionValueKeyCcNumber,
	FormFillActionValueKeyCcExpMonth,
	FormFillActionValueKeyCcExpYear,
	FormFillActionValueKeyCcExp,
	FormFillActionValueKeyCcCvv,
	FormFillActionValueKeyUsername,
	FormFillActionValueKeyPassword,
	FormFillActionValueKeyCurrentPassword,
	FormFillActionValueKeyNewPassword,
	FormFillActionValueKeyTotp,
}

// IsValidFormFillActionKey checks if a string is a valid FormFillActionKey
func IsValidFormFillActionKey(key string) bool {
	return validFormFillActionKeys[FormFillActionKey(key)]
}

// ValidateFormFillActionKeys checks that all keys in a map are valid FormFillActionKey values
func ValidateFormFillActionKeys(keys []string) error {
	var invalid []string
	for _, k := range keys {
		if !IsValidFormFillActionKey(k) {
			invalid = append(invalid, k)
		}
	}
	if len(invalid) > 0 {
		return fmt.Errorf("invalid FormFillActionKey(s): %v; valid keys: %v", invalid, AllFormFillActionKeys)
	}
	return nil
}

// RunDetailResponseKey represents valid keys for RunDetailResponse.payloads
type RunDetailResponseKey string

// Valid RunDetailResponseKey values
const (
	RunDetailResponsePayloadsKeyResult    RunDetailResponseKey = "result"
	RunDetailResponsePayloadsKeyLogs      RunDetailResponseKey = "logs"
	RunDetailResponsePayloadsKeyVariables RunDetailResponseKey = "variables"
)

// validRunDetailResponseKeys is the set of all valid RunDetailResponseKey values
var validRunDetailResponseKeys = map[RunDetailResponseKey]bool{
	RunDetailResponsePayloadsKeyResult:    true,
	RunDetailResponsePayloadsKeyLogs:      true,
	RunDetailResponsePayloadsKeyVariables: true,
}

// AllRunDetailResponseKeys returns all valid RunDetailResponseKey values
var AllRunDetailResponseKeys = []RunDetailResponseKey{
	RunDetailResponsePayloadsKeyResult,
	RunDetailResponsePayloadsKeyLogs,
	RunDetailResponsePayloadsKeyVariables,
}

// IsValidRunDetailResponseKey checks if a string is a valid RunDetailResponseKey
func IsValidRunDetailResponseKey(key string) bool {
	return validRunDetailResponseKeys[RunDetailResponseKey(key)]
}

// ValidateRunDetailResponseKeys checks that all keys in a map are valid RunDetailResponseKey values
func ValidateRunDetailResponseKeys(keys []string) error {
	var invalid []string
	for _, k := range keys {
		if !IsValidRunDetailResponseKey(k) {
			invalid = append(invalid, k)
		}
	}
	if len(invalid) > 0 {
		return fmt.Errorf("invalid RunDetailResponseKey(s): %v; valid keys: %v", invalid, AllRunDetailResponseKeys)
	}
	return nil
}

// RunDetailResponseKey represents valid keys for RunDetailResponse.payload_urls
type RunDetailResponseKey string

// Valid RunDetailResponseKey values
const (
	RunDetailResponsePayload_urlsKeyResult    RunDetailResponseKey = "result"
	RunDetailResponsePayload_urlsKeyLogs      RunDetailResponseKey = "logs"
	RunDetailResponsePayload_urlsKeyVariables RunDetailResponseKey = "variables"
)

// validRunDetailResponseKeys is the set of all valid RunDetailResponseKey values
var validRunDetailResponseKeys = map[RunDetailResponseKey]bool{
	RunDetailResponsePayload_urlsKeyResult:    true,
	RunDetailResponsePayload_urlsKeyLogs:      true,
	RunDetailResponsePayload_urlsKeyVariables: true,
}

// AllRunDetailResponseKeys returns all valid RunDetailResponseKey values
var AllRunDetailResponseKeys = []RunDetailResponseKey{
	RunDetailResponsePayload_urlsKeyResult,
	RunDetailResponsePayload_urlsKeyLogs,
	RunDetailResponsePayload_urlsKeyVariables,
}

// IsValidRunDetailResponseKey checks if a string is a valid RunDetailResponseKey
func IsValidRunDetailResponseKey(key string) bool {
	return validRunDetailResponseKeys[RunDetailResponseKey(key)]
}

// ValidateRunDetailResponseKeys checks that all keys in a map are valid RunDetailResponseKey values
func ValidateRunDetailResponseKeys(keys []string) error {
	var invalid []string
	for _, k := range keys {
		if !IsValidRunDetailResponseKey(k) {
			invalid = append(invalid, k)
		}
	}
	if len(invalid) > 0 {
		return fmt.Errorf("invalid RunDetailResponseKey(s): %v; valid keys: %v", invalid, AllRunDetailResponseKeys)
	}
	return nil
}

// RunUpdateRequestKey represents valid keys for RunUpdateRequest.payloads
type RunUpdateRequestKey string

// Valid RunUpdateRequestKey values
const (
	RunUpdateRequestPayloadsKeyResult    RunUpdateRequestKey = "result"
	RunUpdateRequestPayloadsKeyLogs      RunUpdateRequestKey = "logs"
	RunUpdateRequestPayloadsKeyVariables RunUpdateRequestKey = "variables"
)

// validRunUpdateRequestKeys is the set of all valid RunUpdateRequestKey values
var validRunUpdateRequestKeys = map[RunUpdateRequestKey]bool{
	RunUpdateRequestPayloadsKeyResult:    true,
	RunUpdateRequestPayloadsKeyLogs:      true,
	RunUpdateRequestPayloadsKeyVariables: true,
}

// AllRunUpdateRequestKeys returns all valid RunUpdateRequestKey values
var AllRunUpdateRequestKeys = []RunUpdateRequestKey{
	RunUpdateRequestPayloadsKeyResult,
	RunUpdateRequestPayloadsKeyLogs,
	RunUpdateRequestPayloadsKeyVariables,
}

// IsValidRunUpdateRequestKey checks if a string is a valid RunUpdateRequestKey
func IsValidRunUpdateRequestKey(key string) bool {
	return validRunUpdateRequestKeys[RunUpdateRequestKey(key)]
}

// ValidateRunUpdateRequestKeys checks that all keys in a map are valid RunUpdateRequestKey values
func ValidateRunUpdateRequestKeys(keys []string) error {
	var invalid []string
	for _, k := range keys {
		if !IsValidRunUpdateRequestKey(k) {
			invalid = append(invalid, k)
		}
	}
	if len(invalid) > 0 {
		return fmt.Errorf("invalid RunUpdateRequestKey(s): %v; valid keys: %v", invalid, AllRunUpdateRequestKeys)
	}
	return nil
}
