// Code generated by gen-property-names.py DO NOT EDIT.
package api

import "fmt"

// FormFillActionKey represents valid keys for FormFillAction.value
type FormFillActionKey string

// Valid FormFillActionKey values
const (
	FormFillActionValueKeyTitle           FormFillActionKey = "title"
	FormFillActionValueKeyFirstName       FormFillActionKey = "first_name"
	FormFillActionValueKeyMiddleName      FormFillActionKey = "middle_name"
	FormFillActionValueKeyLastName        FormFillActionKey = "last_name"
	FormFillActionValueKeyFullName        FormFillActionKey = "full_name"
	FormFillActionValueKeyEmail           FormFillActionKey = "email"
	FormFillActionValueKeyCompany         FormFillActionKey = "company"
	FormFillActionValueKeyAddress1        FormFillActionKey = "address1"
	FormFillActionValueKeyAddress2        FormFillActionKey = "address2"
	FormFillActionValueKeyAddress3        FormFillActionKey = "address3"
	FormFillActionValueKeyCity            FormFillActionKey = "city"
	FormFillActionValueKeyState           FormFillActionKey = "state"
	FormFillActionValueKeyPostalCode      FormFillActionKey = "postal_code"
	FormFillActionValueKeyCountry         FormFillActionKey = "country"
	FormFillActionValueKeyPhone           FormFillActionKey = "phone"
	FormFillActionValueKeyCcName          FormFillActionKey = "cc_name"
	FormFillActionValueKeyCcNumber        FormFillActionKey = "cc_number"
	FormFillActionValueKeyCcExpMonth      FormFillActionKey = "cc_exp_month"
	FormFillActionValueKeyCcExpYear       FormFillActionKey = "cc_exp_year"
	FormFillActionValueKeyCcExp           FormFillActionKey = "cc_exp"
	FormFillActionValueKeyCcCvv           FormFillActionKey = "cc_cvv"
	FormFillActionValueKeyUsername        FormFillActionKey = "username"
	FormFillActionValueKeyPassword        FormFillActionKey = "password"
	FormFillActionValueKeyCurrentPassword FormFillActionKey = "current_password"
	FormFillActionValueKeyNewPassword     FormFillActionKey = "new_password"
	FormFillActionValueKeyTotp            FormFillActionKey = "totp"
)

// validFormFillActionKeys is the set of all valid FormFillActionKey values
var validFormFillActionKeys = map[FormFillActionKey]bool{
	FormFillActionValueKeyTitle:           true,
	FormFillActionValueKeyFirstName:       true,
	FormFillActionValueKeyMiddleName:      true,
	FormFillActionValueKeyLastName:        true,
	FormFillActionValueKeyFullName:        true,
	FormFillActionValueKeyEmail:           true,
	FormFillActionValueKeyCompany:         true,
	FormFillActionValueKeyAddress1:        true,
	FormFillActionValueKeyAddress2:        true,
	FormFillActionValueKeyAddress3:        true,
	FormFillActionValueKeyCity:            true,
	FormFillActionValueKeyState:           true,
	FormFillActionValueKeyPostalCode:      true,
	FormFillActionValueKeyCountry:         true,
	FormFillActionValueKeyPhone:           true,
	FormFillActionValueKeyCcName:          true,
	FormFillActionValueKeyCcNumber:        true,
	FormFillActionValueKeyCcExpMonth:      true,
	FormFillActionValueKeyCcExpYear:       true,
	FormFillActionValueKeyCcExp:           true,
	FormFillActionValueKeyCcCvv:           true,
	FormFillActionValueKeyUsername:        true,
	FormFillActionValueKeyPassword:        true,
	FormFillActionValueKeyCurrentPassword: true,
	FormFillActionValueKeyNewPassword:     true,
	FormFillActionValueKeyTotp:            true,
}

// AllFormFillActionKeys returns all valid FormFillActionKey values
var AllFormFillActionKeys = []FormFillActionKey{
	FormFillActionValueKeyTitle,
	FormFillActionValueKeyFirstName,
	FormFillActionValueKeyMiddleName,
	FormFillActionValueKeyLastName,
	FormFillActionValueKeyFullName,
	FormFillActionValueKeyEmail,
	FormFillActionValueKeyCompany,
	FormFillActionValueKeyAddress1,
	FormFillActionValueKeyAddress2,
	FormFillActionValueKeyAddress3,
	FormFillActionValueKeyCity,
	FormFillActionValueKeyState,
	FormFillActionValueKeyPostalCode,
	FormFillActionValueKeyCountry,
	FormFillActionValueKeyPhone,
	FormFillActionValueKeyCcName,
	FormFillActionValueKeyCcNumber,
	FormFillActionValueKeyCcExpMonth,
	FormFillActionValueKeyCcExpYear,
	FormFillActionValueKeyCcExp,
	FormFillActionValueKeyCcCvv,
	FormFillActionValueKeyUsername,
	FormFillActionValueKeyPassword,
	FormFillActionValueKeyCurrentPassword,
	FormFillActionValueKeyNewPassword,
	FormFillActionValueKeyTotp,
}

// IsValidFormFillActionKey checks if a string is a valid FormFillActionKey
func IsValidFormFillActionKey(key string) bool {
	return validFormFillActionKeys[FormFillActionKey(key)]
}

// ValidateFormFillActionKeys checks that all keys in a map are valid FormFillActionKey values
func ValidateFormFillActionKeys(keys []string) error {
	var invalid []string
	for _, k := range keys {
		if !IsValidFormFillActionKey(k) {
			invalid = append(invalid, k)
		}
	}
	if len(invalid) > 0 {
		return fmt.Errorf("invalid FormFillActionKey(s): %v; valid keys: %v", invalid, AllFormFillActionKeys)
	}
	return nil
}
