// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// readJSONFile reads JSON from a file path (supports @file.json syntax)
func readJSONFile(path string) (interface{}, error) {
	// Remove @ prefix if present
	filePath := strings.TrimPrefix(path, "@")
	
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to read file %s: %w", filePath, err)
	}
	
	var result interface{}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, fmt.Errorf("failed to parse JSON from %s: %w", filePath, err)
	}
	
	return result, nil
}

// AgentStart command flags
var (
	// The URL that the agent should start on (optional)
	AgentStartUrl string

	// JSON file input: response-format
	AgentStartResponseFormat string

	// The maximum number of steps the agent should take
	AgentStartMaxSteps int

	// The persona to use for the agent
	AgentStartPersonaId string

	// [Experimental] The step from which the agent should gather information from in the session. If none, fresh memory
	AgentStartSessionOffset int

	// The ID of the session to run the agent on
	AgentStartSessionId string

	// The task that the agent should perform
	AgentStartTask string

	// The reasoning model to use
	AgentStartReasoningModel string

	// Whether to use vision for the agent. Not all reasoning models support vision.
	AgentStartUseVision bool

	// The vault to use for the agent
	AgentStartVaultId string

)

// RegisterAgentStartFlags registers all flags for AgentStart command
func RegisterAgentStartFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&AgentStartUrl, "url", "", "The URL that the agent should start on (optional)")
	cmd.Flags().StringVar(&AgentStartResponseFormat, "response-format-json", "", "response-format configuration (JSON file path, e.g., @config.json)")
	cmd.Flags().IntVar(&AgentStartMaxSteps, "max-steps", 0, "The maximum number of steps the agent should take")
	cmd.Flags().StringVar(&AgentStartPersonaId, "persona-id", "", "The persona to use for the agent")
	cmd.Flags().IntVar(&AgentStartSessionOffset, "session-offset", 0, "[Experimental] The step from which the agent should gather information from in the session. If none, fresh memory")
	cmd.Flags().StringVar(&AgentStartSessionId, "session-id", "", "The ID of the session to run the agent on")
	cmd.Flags().StringVar(&AgentStartTask, "task", "", "The task that the agent should perform")
	cmd.Flags().StringVar(&AgentStartReasoningModel, "reasoning-model", "", "The reasoning model to use (openai/gpt-4o, gemini/gemini-2.0-flash, vertex_ai/gemini-2.0-flash, vertex_ai/gemini-2.5-flash, openrouter/google/gemma-3-27b-it, cerebras/llama-3.3-70b, groq/llama-3.3-70b-versatile, perplexity/sonar-pro, deepseek/deepseek-r1, together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo, anthropic/claude-sonnet-4-5-20250929, moonshot/kimi-k2.5)")
	cmd.Flags().BoolVar(&AgentStartUseVision, "use-vision", false, "Whether to use vision for the agent. Not all reasoning models support vision.")
	cmd.Flags().StringVar(&AgentStartVaultId, "vault-id", "", "The vault to use for the agent")
}

// BuildAgentStartRequest builds the API request from CLI flags
func BuildAgentStartRequest(cmd *cobra.Command) (*api.ApiAgentStartRequest, error) {
	body := &api.ApiAgentStartRequest{}

	if AgentStartUrl != "" {
		body.Url = &AgentStartUrl
	}

	// response_format (JSON file input)
	if AgentStartResponseFormat != "" {
		data, err := readJSONFile(AgentStartResponseFormat)
		if err != nil {
			return nil, fmt.Errorf("failed to read response-format: %w", err)
		}
		body.ResponseFormat = data
	}

	if AgentStartMaxSteps > 0 {
		body.MaxSteps = &AgentStartMaxSteps
	}

	if AgentStartPersonaId != "" {
		body.PersonaId = &AgentStartPersonaId
	}

	if AgentStartSessionOffset > 0 {
		body.SessionOffset = &AgentStartSessionOffset
	}

	if cmd.Flags().Changed("session-id") {
		body.SessionId = AgentStartSessionId
	}

	if cmd.Flags().Changed("task") {
		body.Task = AgentStartTask
	}

	if AgentStartReasoningModel != "" {
		var val api.ApiAgentStartRequest_ReasoningModel
		if err := val.FromApiAgentStartRequestReasoningModel1(AgentStartReasoningModel); err != nil {
			return nil, fmt.Errorf("invalid reasoning-model: %w", err)
		}
		body.ReasoningModel = &val
	}

	if cmd.Flags().Changed("use-vision") {
		body.UseVision = &AgentStartUseVision
	}

	if AgentStartVaultId != "" {
		body.VaultId = &AgentStartVaultId
	}

	return body, nil
}
