// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// FunctionScheduleSet command flags
var (
	// AWS EventBridge schedule expression. Six space-separated fields, minutes first: `minutes hours day-of-month month day-of-week year`. This is neither five-field Unix crontab nor the seconds-first six-field dialect used by Quartz and cron-parser. Exactly one of day-of-month and day-of-week must be `?`, the other must be a real value. Schedules fire in UTC. Example: `0 12 ? * * *` runs daily at noon UTC. `rate(...)` expressions such as `rate(1 hour)` are accepted too.
	FunctionScheduleSetCron string
)

// RegisterFunctionScheduleSetFlags registers all flags for FunctionScheduleSet command
func RegisterFunctionScheduleSetFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&FunctionScheduleSetCron, "cron", "", "AWS EventBridge schedule expression. Six space-separated fields, minutes first: `minutes hours day-of-month month day-of-week year`. This is neither five-field Unix crontab nor the seconds-first six-field dialect used by Quartz and cron-parser. Exactly one of day-of-month and day-of-week must be `?`, the other must be a real value. Schedules fire in UTC. Example: `0 12 ? * * *` runs daily at noon UTC. `rate(...)` expressions such as `rate(1 hour)` are accepted too.")
}

// BuildFunctionScheduleSetRequest builds the API request from CLI flags
func BuildFunctionScheduleSetRequest(cmd *cobra.Command) (*api.FunctionScheduleCreateRequest, error) {
	body := &api.FunctionScheduleCreateRequest{}

	if cmd.Flags().Changed("cron") {
		if FunctionScheduleSetCron == "" {
			return nil, fmt.Errorf("--cron cannot be empty")
		}
		body.Cron = FunctionScheduleSetCron
	}

	return body, nil
}
