// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// FunctionConfigure command flags
var (
	FunctionConfigureDescription string

	FunctionConfigureDomain string

	// Notes for whoever calls this function: how long a run takes, what the variables mean, what it trips over
	FunctionConfigureInstructions string

	FunctionConfigureName string

	// JSON document: response-format
	FunctionConfigureResponseFormat string

	// Let an agent repair the function when a run fails
	FunctionConfigureSelfHealing bool
)

// RegisterFunctionConfigureFlags registers all flags for FunctionConfigure command
func RegisterFunctionConfigureFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&FunctionConfigureDescription, "description", "", "description")
	cmd.Flags().StringVar(&FunctionConfigureDomain, "domain", "", "domain")
	cmd.Flags().StringVar(&FunctionConfigureInstructions, "run-instructions", "", "Notes for whoever calls this function: how long a run takes, what the variables mean, what it trips over")
	cmd.Flags().StringVar(&FunctionConfigureName, "name", "", "name")
	cmd.Flags().StringVar(&FunctionConfigureResponseFormat, "response-format", "", "JSON Schema of run()'s return value, computed by the caller from its pydantic model, as inline JSON, @file, or - for stdin")
	cmd.Flags().BoolVar(&FunctionConfigureSelfHealing, "self-healing", false, "Let an agent repair the function when a run fails")
}

// BuildFunctionConfigureRequest builds the API request from CLI flags
func BuildFunctionConfigureRequest(cmd *cobra.Command) (*api.FunctionMetadataUpdateRequest, error) {
	body := &api.FunctionMetadataUpdateRequest{}

	if FunctionConfigureDescription != "" {
		body.Description = &FunctionConfigureDescription
	}

	if FunctionConfigureDomain != "" {
		body.Domain = &FunctionConfigureDomain
	}

	if FunctionConfigureInstructions != "" {
		body.Instructions = &FunctionConfigureInstructions
	}

	if FunctionConfigureName != "" {
		body.Name = &FunctionConfigureName
	}

	// response_format (JSON document)
	responseFormat, err := readJSONDocumentFlag(cmd, "response-format", FunctionConfigureResponseFormat)
	if err != nil {
		return nil, err
	}
	if responseFormat != "" {
		var document map[string]interface{}
		decoder := json.NewDecoder(strings.NewReader(responseFormat))
		decoder.UseNumber()
		if err := decoder.Decode(&document); err != nil {
			return nil, fmt.Errorf("failed to parse --response-format: %w", err)
		}
		body.ResponseFormat = &document
	}

	if cmd.Flags().Changed("self-healing") {
		body.SelfHealing = &FunctionConfigureSelfHealing
	}

	return body, nil
}
