// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// FunctionRollback command flags
var (
	// A version from the function's `versions` history to restore
	FunctionRollbackVersion string
)

// RegisterFunctionRollbackFlags registers all flags for FunctionRollback command
func RegisterFunctionRollbackFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&FunctionRollbackVersion, "version", "", "A version from the function's `versions` history to restore")
}

// BuildFunctionRollbackRequest builds the API request from CLI flags
func BuildFunctionRollbackRequest(cmd *cobra.Command) (*api.FunctionRollbackRequest, error) {
	body := &api.FunctionRollbackRequest{}

	if cmd.Flags().Changed("version") {
		if FunctionRollbackVersion == "" {
			return nil, fmt.Errorf("--version cannot be empty")
		}
		body.Version = FunctionRollbackVersion
	}

	return body, nil
}
