// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"bytes"
	"fmt"
	"io"
	"mime/multipart"
	"os"
	"path/filepath"
	"strconv"

	"github.com/spf13/cobra"
)

// FunctionCreate command flags
var (
	// Function description
	FunctionCreateDescription string

	// File upload: file holds a path, not the contents
	FunctionCreateFile string

	// Function name
	FunctionCreateName string

	// JSON document: response-format
	FunctionCreateResponseFormat string

	// Make function public
	FunctionCreateShared bool
)

// RegisterFunctionCreateFlags registers all flags for FunctionCreate command
func RegisterFunctionCreateFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&FunctionCreateDescription, "description", "", "Function description")
	cmd.Flags().StringVar(&FunctionCreateFile, "file", "", "Path to function file (required)")
	_ = cmd.MarkFlagRequired("file")
	cmd.Flags().StringVar(&FunctionCreateName, "name", "", "Function name")
	cmd.Flags().StringVar(&FunctionCreateResponseFormat, "response-format", "", "JSON Schema of run()'s return value, computed by the caller from its pydantic model, as inline JSON, @file, or - for stdin")
	cmd.Flags().BoolVar(&FunctionCreateShared, "shared", false, "Make function public (API default: false)")
}

// BuildFunctionCreateBody encodes the multipart request body from CLI flags.
// It returns the body and the Content-Type header describing its boundary.
func BuildFunctionCreateBody(cmd *cobra.Command) (io.Reader, string, error) {
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)

	// description
	if FunctionCreateDescription != "" {
		if err := writer.WriteField("description", FunctionCreateDescription); err != nil {
			return nil, "", fmt.Errorf("failed to write description field: %w", err)
		}
	}

	// file (file upload)
	if FunctionCreateFile == "" {
		return nil, "", fmt.Errorf("--file is required")
	}
	file, err := os.Open(FunctionCreateFile)
	if err != nil {
		return nil, "", fmt.Errorf("failed to open file: %w", err)
	}
	defer func() { _ = file.Close() }()
	part, err := writer.CreateFormFile("file", filepath.Base(FunctionCreateFile))
	if err != nil {
		return nil, "", fmt.Errorf("failed to create form file: %w", err)
	}
	if _, err := io.Copy(part, file); err != nil {
		return nil, "", fmt.Errorf("failed to copy file data: %w", err)
	}

	// name
	if FunctionCreateName != "" {
		if err := writer.WriteField("name", FunctionCreateName); err != nil {
			return nil, "", fmt.Errorf("failed to write name field: %w", err)
		}
	}

	// response_format (JSON document)
	responseFormat, err := readJSONDocumentFlag(cmd, "response-format", FunctionCreateResponseFormat)
	if err != nil {
		return nil, "", err
	}
	if responseFormat != "" {
		if err := writer.WriteField("response_format", responseFormat); err != nil {
			return nil, "", fmt.Errorf("failed to write response_format field: %w", err)
		}
	}

	// shared
	if cmd.Flags().Changed("shared") {
		if err := writer.WriteField("shared", strconv.FormatBool(FunctionCreateShared)); err != nil {
			return nil, "", fmt.Errorf("failed to write shared field: %w", err)
		}
	}

	if err := writer.Close(); err != nil {
		return nil, "", fmt.Errorf("failed to finalize request body: %w", err)
	}

	return &body, writer.FormDataContentType(), nil
}
