// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// FunctionScheduleSet command flags
var (
	// Cron expression, e.g. "0 12 ? * * *" for daily at noon UTC (required)
	FunctionScheduleSetCron string
)

// RegisterFunctionScheduleSetFlags registers all flags for FunctionScheduleSet command
func RegisterFunctionScheduleSetFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&FunctionScheduleSetCron, "cron", "", "Cron expression, e.g. \"0 12 ? * * *\" for daily at noon UTC (required)")
}

// BuildFunctionScheduleSetRequest builds the API request from CLI flags
func BuildFunctionScheduleSetRequest(cmd *cobra.Command) (*api.FunctionScheduleCreateRequest, error) {
	body := &api.FunctionScheduleCreateRequest{}

	if cmd.Flags().Changed("cron") {
		if FunctionScheduleSetCron == "" {
			return nil, fmt.Errorf("--cron cannot be empty")
		}
		body.Cron = FunctionScheduleSetCron
	}

	return body, nil
}
