// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"bytes"
	"fmt"
	"io"
	"mime/multipart"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

// FunctionUpdate command flags
var (
	// File upload: file holds a path, not the contents
	FunctionUpdateFile string

	// JSON document: response-format
	FunctionUpdateResponseFormat string
)

// RegisterFunctionUpdateFlags registers all flags for FunctionUpdate command
func RegisterFunctionUpdateFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&FunctionUpdateFile, "file", "", "Path to updated function file (required)")
	_ = cmd.MarkFlagRequired("file")
	cmd.Flags().StringVar(&FunctionUpdateResponseFormat, "response-format", "", "JSON Schema of run()'s return value, computed by the caller from its pydantic model, as inline JSON, @file, or - for stdin")
}

// BuildFunctionUpdateBody encodes the multipart request body from CLI flags.
// It returns the body and the Content-Type header describing its boundary.
func BuildFunctionUpdateBody(cmd *cobra.Command) (io.Reader, string, error) {
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)

	// file (file upload)
	if FunctionUpdateFile == "" {
		return nil, "", fmt.Errorf("--file is required")
	}
	file, err := os.Open(FunctionUpdateFile)
	if err != nil {
		return nil, "", fmt.Errorf("failed to open file: %w", err)
	}
	defer func() { _ = file.Close() }()
	part, err := writer.CreateFormFile("file", filepath.Base(FunctionUpdateFile))
	if err != nil {
		return nil, "", fmt.Errorf("failed to create form file: %w", err)
	}
	if _, err := io.Copy(part, file); err != nil {
		return nil, "", fmt.Errorf("failed to copy file data: %w", err)
	}

	// response_format (JSON document)
	responseFormat, err := readJSONDocumentFlag(cmd, "response-format", FunctionUpdateResponseFormat)
	if err != nil {
		return nil, "", err
	}
	if responseFormat != "" {
		if err := writer.WriteField("response_format", responseFormat); err != nil {
			return nil, "", fmt.Errorf("failed to write response_format field: %w", err)
		}
	}

	if err := writer.Close(); err != nil {
		return nil, "", fmt.Errorf("failed to finalize request body: %w", err)
	}

	return &body, writer.FormDataContentType(), nil
}
