// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// FunctionConfigure command flags
var (
	// Instructions the self-healing agent follows when the function breaks
	FunctionConfigureInstructions string

	// Let the agent repair the function when a run fails
	FunctionConfigureSelfHealing bool
)

// RegisterFunctionConfigureFlags registers all flags for FunctionConfigure command
func RegisterFunctionConfigureFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&FunctionConfigureInstructions, "instructions", "", "Instructions the self-healing agent follows when the function breaks")
	cmd.Flags().BoolVar(&FunctionConfigureSelfHealing, "self-healing", false, "Let the agent repair the function when a run fails")
}

// BuildFunctionConfigureRequest builds the API request from CLI flags
func BuildFunctionConfigureRequest(cmd *cobra.Command) (*api.FunctionMetadataUpdateRequest, error) {
	body := &api.FunctionMetadataUpdateRequest{}

	if FunctionConfigureInstructions != "" {
		body.Instructions = &FunctionConfigureInstructions
	}

	if cmd.Flags().Changed("self-healing") {
		body.SelfHealing = &FunctionConfigureSelfHealing
	}

	return body, nil
}
