// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// PersonaCreate command flags
var (
	// Whether to create a vault for the persona
	PersonaCreateCreateVault bool

	// Whether to create a phone number for the persona
	PersonaCreateCreatePhoneNumber bool

)

// RegisterPersonaCreateFlags registers all flags for PersonaCreate command
func RegisterPersonaCreateFlags(cmd *cobra.Command) {
	cmd.Flags().BoolVar(&PersonaCreateCreateVault, "create-vault", false, "Whether to create a vault for the persona")
	cmd.Flags().BoolVar(&PersonaCreateCreatePhoneNumber, "create-phone-number", false, "Whether to create a phone number for the persona")
}

// BuildPersonaCreateRequest builds the API request from CLI flags
func BuildPersonaCreateRequest(cmd *cobra.Command) (*api.PersonaCreateRequest, error) {
	body := &api.PersonaCreateRequest{}

	if cmd.Flags().Changed("create-vault") {
		body.CreateVault = &PersonaCreateCreateVault
	}

	if cmd.Flags().Changed("create-phone-number") {
		body.CreatePhoneNumber = &PersonaCreateCreatePhoneNumber
	}

	return body, nil
}
