// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// PersonaUpdate command flags
var (
	// New name for the persona
	PersonaUpdateName string
)

// RegisterPersonaUpdateFlags registers all flags for PersonaUpdate command
func RegisterPersonaUpdateFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&PersonaUpdateName, "name", "", "New name for the persona")
}

// BuildPersonaUpdateRequest builds the API request from CLI flags
func BuildPersonaUpdateRequest(cmd *cobra.Command) (*api.PersonaUpdateRequest, error) {
	body := &api.PersonaUpdateRequest{}

	if cmd.Flags().Changed("name") {
		if PersonaUpdateName == "" {
			return nil, fmt.Errorf("--name cannot be empty")
		}
		body.Name = PersonaUpdateName
	}

	return body, nil
}
