// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// ProfileCreate command flags
var (
	// Name of the profile
	ProfileCreateName string

)

// RegisterProfileCreateFlags registers all flags for ProfileCreate command
func RegisterProfileCreateFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&ProfileCreateName, "name", "", "Name of the profile")
}

// BuildProfileCreateRequest builds the API request from CLI flags
func BuildProfileCreateRequest(cmd *cobra.Command) (*api.ProfileCreateRequest, error) {
	body := &api.ProfileCreateRequest{}

	if ProfileCreateName != "" {
		body.Name = &ProfileCreateName
	}

	return body, nil
}
