// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// SessionStart command flags
var (
	// Whether to run the session in headless mode.
	SessionStartHeadless bool

	// Maximum session lifetime in minutes (absolute maximum, not affected by activity).
	SessionStartMaxDurationMinutes int

	// The browser type to use. Can be chromium, chrome or firefox.
	SessionStartBrowserType string

	// The user agent to use for the session
	SessionStartUserAgent string

	// The CDP URL of another remote session provider.
	SessionStartCdpUrl string

	// Overwrite the chrome instance arguments
	SessionStartChromeArgs []string

	// The width of the viewport
	SessionStartViewportWidth int

	// The type of screenshot to use for the session.
	SessionStartScreenshotType string

	// Idle timeout in minutes. Session closes after this period of inactivity (resets on each operation).
	SessionStartIdleTimeoutMinutes int

	// Whether to try to automatically solve captchas
	SessionStartSolveCaptchas bool

	// The height of the viewport
	SessionStartViewportHeight int

	// Whether FileStorage should be attached to the session.
	SessionStartUseFileStorage bool

	// Flattened: profile object
	SessionStartProfilePersist bool
	SessionStartProfileId      string
)

// RegisterSessionStartFlags registers all flags for SessionStart command
func RegisterSessionStartFlags(cmd *cobra.Command) {
	cmd.Flags().BoolVar(&SessionStartHeadless, "headless", false, "Whether to run the session in headless mode.")
	cmd.Flags().IntVar(&SessionStartMaxDurationMinutes, "max-duration-minutes", 0, "Maximum session lifetime in minutes (absolute maximum, not affected by activity).")
	cmd.Flags().StringVar(&SessionStartBrowserType, "browser-type", "", "The browser type to use. Can be chromium, chrome or firefox. (chromium, chrome, firefox, chrome-nightly, chrome-turbo)")
	cmd.Flags().StringVar(&SessionStartUserAgent, "user-agent", "", "The user agent to use for the session")
	cmd.Flags().StringVar(&SessionStartCdpUrl, "cdp-url", "", "The CDP URL of another remote session provider.")
	cmd.Flags().StringSliceVar(&SessionStartChromeArgs, "chrome-args", []string{}, "Overwrite the chrome instance arguments (repeatable)")
	cmd.Flags().IntVar(&SessionStartViewportWidth, "viewport-width", 0, "The width of the viewport")
	cmd.Flags().StringVar(&SessionStartScreenshotType, "screenshot-type", "", "The type of screenshot to use for the session. (raw, full, last_action)")
	cmd.Flags().IntVar(&SessionStartIdleTimeoutMinutes, "idle-timeout-minutes", 0, "Idle timeout in minutes. Session closes after this period of inactivity (resets on each operation).")
	cmd.Flags().BoolVar(&SessionStartSolveCaptchas, "solve-captchas", false, "Whether to try to automatically solve captchas")
	cmd.Flags().IntVar(&SessionStartViewportHeight, "viewport-height", 0, "The height of the viewport")
	cmd.Flags().BoolVar(&SessionStartUseFileStorage, "use-file-storage", false, "Whether FileStorage should be attached to the session.")
	// profile (flattened object)
	cmd.Flags().BoolVar(&SessionStartProfilePersist, "profile-persist", false, "Whether to save browser state to profile on session close")
	cmd.Flags().StringVar(&SessionStartProfileId, "profile-id", "", "Profile ID to use for this session")
}

// BuildSessionStartRequest builds the API request from CLI flags
func BuildSessionStartRequest(cmd *cobra.Command) (*api.ApiSessionStartRequest, error) {
	body := &api.ApiSessionStartRequest{}

	if cmd.Flags().Changed("headless") {
		body.Headless = &SessionStartHeadless
	}

	if SessionStartMaxDurationMinutes > 0 {
		body.MaxDurationMinutes = &SessionStartMaxDurationMinutes
	}

	if SessionStartBrowserType != "" {
		var val api.ApiSessionStartRequest_BrowserType
		if err := val.FromApiSessionStartRequestBrowserType1(SessionStartBrowserType); err != nil {
			return nil, fmt.Errorf("invalid browser-type: %w", err)
		}
		body.BrowserType = &val
	}

	if SessionStartUserAgent != "" {
		body.UserAgent = &SessionStartUserAgent
	}

	if SessionStartCdpUrl != "" {
		body.CdpUrl = &SessionStartCdpUrl
	}

	if len(SessionStartChromeArgs) > 0 {
		// Convert string slice to interface slice
		args := make([]interface{}, len(SessionStartChromeArgs))
		for i, arg := range SessionStartChromeArgs {
			args[i] = arg
		}
		body.ChromeArgs = &args
	}

	if SessionStartViewportWidth > 0 {
		body.ViewportWidth = &SessionStartViewportWidth
	}

	if SessionStartScreenshotType != "" {
		var val api.ApiSessionStartRequest_ScreenshotType
		if err := val.FromApiSessionStartRequestScreenshotType1(SessionStartScreenshotType); err != nil {
			return nil, fmt.Errorf("invalid screenshot-type: %w", err)
		}
		body.ScreenshotType = &val
	}

	if SessionStartIdleTimeoutMinutes > 0 {
		body.IdleTimeoutMinutes = &SessionStartIdleTimeoutMinutes
	}

	if cmd.Flags().Changed("solve-captchas") {
		body.SolveCaptchas = &SessionStartSolveCaptchas
	}

	if SessionStartViewportHeight > 0 {
		body.ViewportHeight = &SessionStartViewportHeight
	}

	if cmd.Flags().Changed("use-file-storage") {
		body.UseFileStorage = &SessionStartUseFileStorage
	}

	// profile (flattened)
	if cmd.Flags().Changed("profile-persist") || SessionStartProfileId != "" {
		body.Profile = api.SessionProfile{
			Persist: &SessionStartProfilePersist,
			Id:      SessionStartProfileId,
		}
	}

	return body, nil
}
