// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// VaultCredentialsAdd command flags
var (
	VaultCredentialsAddUrl string
)

// RegisterVaultCredentialsAddFlags registers all flags for VaultCredentialsAdd command
func RegisterVaultCredentialsAddFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&VaultCredentialsAddUrl, "url", "", "url")
}

// BuildVaultCredentialsAddRequest builds the API request from CLI flags
func BuildVaultCredentialsAddRequest(cmd *cobra.Command) (*api.AddCredentialsRequest, error) {
	body := &api.AddCredentialsRequest{}

	if cmd.Flags().Changed("url") {
		body.Url = VaultCredentialsAddUrl
	}

	return body, nil
}
