// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// VaultCreate command flags
var (
	// Name of the vault
	VaultCreateName string
)

// RegisterVaultCreateFlags registers all flags for VaultCreate command
func RegisterVaultCreateFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&VaultCreateName, "name", "", "Name of the vault")
}

// BuildVaultCreateRequest builds the API request from CLI flags
func BuildVaultCreateRequest(cmd *cobra.Command) (*api.VaultCreateRequest, error) {
	body := &api.VaultCreateRequest{}

	if VaultCreateName != "" {
		body.Name = &VaultCreateName
	}

	return body, nil
}
