// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// VaultCredentialsAdd command flags
var (
	// Flattened: credentials object
	VaultCredentialsAddCredentialsEmail     string
	VaultCredentialsAddCredentialsMfaSecret string
	VaultCredentialsAddCredentialsPassword  string
	VaultCredentialsAddCredentialsUsername  string

	VaultCredentialsAddUrl string
)

// RegisterVaultCredentialsAddFlags registers all flags for VaultCredentialsAdd command
func RegisterVaultCredentialsAddFlags(cmd *cobra.Command) {
	// credentials (flattened object)
	cmd.Flags().StringVar(&VaultCredentialsAddCredentialsEmail, "email", "", "email")
	cmd.Flags().StringVar(&VaultCredentialsAddCredentialsMfaSecret, "mfa-secret", "", "mfa-secret")
	cmd.Flags().StringVar(&VaultCredentialsAddCredentialsPassword, "password", "", "password")
	cmd.Flags().StringVar(&VaultCredentialsAddCredentialsUsername, "username", "", "username")
	cmd.Flags().StringVar(&VaultCredentialsAddUrl, "url", "", "url")
}

// BuildVaultCredentialsAddRequest builds the API request from CLI flags
func BuildVaultCredentialsAddRequest(cmd *cobra.Command) (*api.AddCredentialsRequest, error) {
	body := &api.AddCredentialsRequest{}

	// credentials: validate required fields when optional fields are provided
	if (VaultCredentialsAddCredentialsEmail != "" || VaultCredentialsAddCredentialsMfaSecret != "" || VaultCredentialsAddCredentialsUsername != "") && !(VaultCredentialsAddCredentialsPassword != "") {
		return nil, fmt.Errorf("credentials requires --password to be set")
	}

	// credentials (flattened) - only set if required fields are provided
	if VaultCredentialsAddCredentialsPassword != "" {
		credentials := api.CredentialsDictInput{
			Password: VaultCredentialsAddCredentialsPassword,
		}
		if VaultCredentialsAddCredentialsEmail != "" {
			credentials.Email = &VaultCredentialsAddCredentialsEmail
		}
		if VaultCredentialsAddCredentialsMfaSecret != "" {
			credentials.MfaSecret = &VaultCredentialsAddCredentialsMfaSecret
		}
		if VaultCredentialsAddCredentialsUsername != "" {
			credentials.Username = &VaultCredentialsAddCredentialsUsername
		}
		body.Credentials = credentials
	}

	if cmd.Flags().Changed("url") {
		if VaultCredentialsAddUrl == "" {
			return nil, fmt.Errorf("--url cannot be empty")
		}
		body.Url = VaultCredentialsAddUrl
	}

	return body, nil
}
