// Code generated by gen-flags DO NOT EDIT.
package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/nottelabs/notte-cli/internal/api"
)

// VaultUpdate command flags
var (
	// New name for the vault
	VaultUpdateName string
)

// RegisterVaultUpdateFlags registers all flags for VaultUpdate command
func RegisterVaultUpdateFlags(cmd *cobra.Command) {
	cmd.Flags().StringVar(&VaultUpdateName, "name", "", "New name for the vault")
}

// BuildVaultUpdateRequest builds the API request from CLI flags
func BuildVaultUpdateRequest(cmd *cobra.Command) (*api.VaultUpdateRequest, error) {
	body := &api.VaultUpdateRequest{}

	if cmd.Flags().Changed("name") {
		if VaultUpdateName == "" {
			return nil, fmt.Errorf("--name cannot be empty")
		}
		body.Name = VaultUpdateName
	}

	return body, nil
}
