# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notte < Formula
  desc "Browser automation CLI for notte.cc"
  homepage "https://notte.cc"
  version "0.0.27"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.27/notte-cli_0.0.27_darwin_amd64.tar.gz"
      sha256 "bd1623ae6976e943790199b249b954e105d0f365e4926410eda759a8b8e9b967"

      define_method(:install) do
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.27/notte-cli_0.0.27_darwin_arm64.tar.gz"
      sha256 "ef66fe321d8f59bb70133596e64e26f55a753c4f467fce921eb8899208e620c4"

      define_method(:install) do
        bin.install "notte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.27/notte-cli_0.0.27_linux_amd64.tar.gz"
      sha256 "59c4b1bc480072a852fb4dc9d95f64ef3069d19fb3fa9bbd24a2c96e71d9d82c"
      define_method(:install) do
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.27/notte-cli_0.0.27_linux_arm64.tar.gz"
      sha256 "3c9a3bffc4b737c18dd05a5c25f6d0e57807fde504fb291ba6c4a5982e3d6a8c"
      define_method(:install) do
        bin.install "notte"
      end
    end
  end

  test do
    system "#{bin}/notte", "version"
  end
end
