# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notte < Formula
  desc "Browser automation CLI for notte.cc"
  homepage "https://notte.cc"
  version "0.0.50"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.50/notte-cli_0.0.50_darwin_amd64.tar.gz"
      sha256 "ce2def8afd51c3915fff94ed7fe2e5c204fb175c2872eec40299016a41bc7034"

      define_method(:install) do
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.50/notte-cli_0.0.50_darwin_arm64.tar.gz"
      sha256 "1f601228c9980599f02f8910feed3359a903dcf5832f8424aa7310995a8dd877"

      define_method(:install) do
        bin.install "notte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.50/notte-cli_0.0.50_linux_amd64.tar.gz"
      sha256 "b02d2f36dce9f326f8bc75665a1ecbe8325585060d81a948806b02c0eed43c44"
      define_method(:install) do
        bin.install "notte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nottelabs/notte-cli/releases/download/v0.0.50/notte-cli_0.0.50_linux_arm64.tar.gz"
      sha256 "22992d51d27630316024c55f2401850aaf4feafa4b55218e312c2a4aca277775"
      define_method(:install) do
        bin.install "notte"
      end
    end
  end

  test do
    system "#{bin}/notte", "version"
  end
end
