#!/usr/bin/env python3
"""
Generates Go enum types from OpenAPI propertyNames constraints.

oapi-codegen doesn't support propertyNames.enum, so this script extracts them
from the spec and generates strongly-typed Go enums with validation functions.
"""

import json
import sys
import textwrap


def find_property_names(schemas: dict) -> list[tuple[str, str, list[str]]]:
    """
    Walk all schemas and find properties that have propertyNames.enum.
    Returns list of (SchemaName, PropertyName, [enum_values]).
    """
    results = []
    for schema_name, schema in schemas.items():
        props = schema.get("properties", {})
        for prop_name, prop_schema in props.items():
            pn = prop_schema.get("propertyNames")
            if pn and "enum" in pn:
                results.append((schema_name, prop_name, pn["enum"]))
    return results


def to_go_const_name(schema: str, prop: str, value: str) -> str:
    """Convert a property name enum value to a Go constant name."""
    parts = value.split("_")
    camel = "".join(p.capitalize() for p in parts)
    return f"{schema}{prop.capitalize()}Key{camel}"


def to_go_type_name(schema: str, prop: str) -> str:
    """Generate the Go type name for a propertyNames enum."""
    return f"{schema}Key"


def generate_go(entries: list[tuple[str, str, list[str]]]) -> str:
    """Generate Go source code for all propertyNames enums."""
    lines = []
    lines.append("// Code generated by gen-property-names.py DO NOT EDIT.")
    lines.append("package api")
    lines.append("")
    lines.append('import "fmt"')
    lines.append("")

    for schema_name, prop_name, values in entries:
        type_name = to_go_type_name(schema_name, prop_name)

        # Type definition
        lines.append(f"// {type_name} represents valid keys for {schema_name}.{prop_name}")
        lines.append(f"type {type_name} string")
        lines.append("")

        # Constants
        lines.append(f"// Valid {type_name} values")
        lines.append("const (")
        for v in values:
            const_name = to_go_const_name(schema_name, prop_name, v)
            lines.append(f'\t{const_name} {type_name} = "{v}"')
        lines.append(")")
        lines.append("")

        # Valid set
        set_var = f"valid{type_name}s"
        lines.append(f"// {set_var} is the set of all valid {type_name} values")
        lines.append(f"var {set_var} = map[{type_name}]bool{{")
        for v in values:
            const_name = to_go_const_name(schema_name, prop_name, v)
            lines.append(f"\t{const_name}: true,")
        lines.append("}")
        lines.append("")

        # All values slice
        all_var = f"All{type_name}s"
        lines.append(f"// {all_var} returns all valid {type_name} values")
        lines.append(f"var {all_var} = []{type_name}{{")
        for v in values:
            const_name = to_go_const_name(schema_name, prop_name, v)
            lines.append(f"\t{const_name},")
        lines.append("}")
        lines.append("")

        # Validation function
        lines.append(f"// IsValid{type_name} checks if a string is a valid {type_name}")
        lines.append(f"func IsValid{type_name}(key string) bool {{")
        lines.append(f"\treturn {set_var}[{type_name}(key)]")
        lines.append("}")
        lines.append("")

        # Validate keys function (for validating a map)
        lines.append(
            f"// Validate{type_name}s checks that all keys in a map are valid {type_name} values"
        )
        lines.append(
            f"func Validate{type_name}s(keys []string) error {{"
        )
        lines.append("\tvar invalid []string")
        lines.append("\tfor _, k := range keys {")
        lines.append(f"\t\tif !IsValid{type_name}(k) {{")
        lines.append("\t\t\tinvalid = append(invalid, k)")
        lines.append("\t\t}")
        lines.append("\t}")
        lines.append("\tif len(invalid) > 0 {")
        lines.append(
            f'\t\treturn fmt.Errorf("invalid {type_name}(s): %v; valid keys: %v", invalid, {all_var})'
        )
        lines.append("\t}")
        lines.append("\treturn nil")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <openapi.json> <output.go>", file=sys.stderr)
        sys.exit(1)

    spec_file = sys.argv[1]
    output_file = sys.argv[2]

    with open(spec_file) as f:
        spec = json.load(f)

    schemas = spec.get("components", {}).get("schemas", {})
    entries = find_property_names(schemas)

    if not entries:
        print("No propertyNames enums found in spec", file=sys.stderr)
        # Still generate an empty file so the build doesn't break
        with open(output_file, "w") as f:
            f.write("// Code generated by gen-property-names.py DO NOT EDIT.\npackage api\n")
        return

    print(f"Found {len(entries)} propertyNames enum(s):")
    for schema, prop, values in entries:
        print(f"  - {schema}.{prop}: {len(values)} values")

    go_code = generate_go(entries)

    with open(output_file, "w") as f:
        f.write(go_code)

    print(f"Generated {output_file}")


if __name__ == "__main__":
    main()
