package main

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
)

// GenerateFlagsFile generates a complete flags file for a command
func GenerateFlagsFile(config *CommandConfig, schemas map[string]*Field) (string, []GenerationError, error) {
	var buf bytes.Buffer
	var errors []GenerationError

	// Work out the imports from what the fields actually need. A multipart
	// body is assembled here rather than handed to the generated client, which
	// offers no encoder for it, so those files import the writer instead of the
	// api package.
	needsFmt := config.IsMultipart
	needsStrconv := false
	needsFileIO := false
	needsJSON := false
	for _, fc := range config.Fields {
		switch fc.Category {
		case CategoryFileUpload:
			needsFileIO = true
			needsFmt = true
		case CategoryJSONDocument:
			needsFmt = true
			// JSON bodies unmarshal the compacted document into a map; multipart
			// bodies write it as a form string and do not need encoding/json here.
			if !config.IsMultipart {
				needsJSON = true
			}
		case CategoryEnumFlag:
			// Actual union types (anyOf with enum + string), not simple enums
			if fc.Field.IsUnionType {
				needsFmt = true
			}
		}
		if config.IsMultipart && fc.Field.Type == "boolean" {
			needsStrconv = true
		}
		// Required string fields need fmt for validation errors
		if fc.Field.Required && fc.Field.Type == "string" {
			needsFmt = true
		}
		// Flattened fields with required sub-fields need fmt for validation
		if fc.Category == CategoryFlattenedFlags {
			for _, subFC := range fc.SubFields {
				if subFC.Field.Required && subFC.Field.Type == "string" {
					needsFmt = true
					break
				}
			}
		}
	}

	// File header
	buf.WriteString("// Code generated by gen-flags DO NOT EDIT.\n")
	buf.WriteString("package cmd\n\n")
	buf.WriteString("import (\n")
	if config.IsMultipart {
		buf.WriteString("\t\"bytes\"\n")
	}
	if needsJSON {
		buf.WriteString("\t\"encoding/json\"\n")
	}
	if needsFmt {
		buf.WriteString("\t\"fmt\"\n")
	}
	if needsFileIO {
		buf.WriteString("\t\"io\"\n")
	}
	if config.IsMultipart {
		buf.WriteString("\t\"mime/multipart\"\n")
	}
	if needsFileIO {
		buf.WriteString("\t\"os\"\n")
		buf.WriteString("\t\"path/filepath\"\n")
	}
	if needsStrconv {
		buf.WriteString("\t\"strconv\"\n")
	}
	buf.WriteString("\n")
	buf.WriteString("\t\"github.com/spf13/cobra\"\n")
	if !config.IsMultipart {
		buf.WriteString("\n")
		buf.WriteString("\t\"github.com/nottelabs/notte-cli/internal/api\"\n")
	}
	buf.WriteString(")\n\n")

	// Generate flag variables
	fmt.Fprintf(&buf, "// %s command flags\n", config.Name)
	buf.WriteString("var (\n")

	for _, fc := range config.Fields {
		if fc.Category == CategorySkipped {
			// Silently skip - no error, no generation
			continue
		}

		if fc.Category == CategoryUnsupported {
			// Collect error
			err := BuildGenerationError(config.RequestBodyType, fc.Field.Name, fc.Field, schemas)
			err.Location = fmt.Sprintf("%s %s body", config.HTTPMethod, config.EndpointPath)
			errors = append(errors, err)
			continue
		}

		switch fc.Category {
		case CategoryFlattenedFlags:
			// Generate variables for sub-fields
			fmt.Fprintf(&buf, "\t// Flattened: %s object\n", fc.FlagName)
			for _, subFC := range fc.SubFields {
				fmt.Fprintf(&buf, "\t%s %s\n", subFC.VarName, subFC.GoType)
			}
		case CategoryJSONDocument:
			fmt.Fprintf(&buf, "\t// JSON document: %s\n", fc.FlagName)
			fmt.Fprintf(&buf, "\t%s string\n", fc.VarName)
		case CategoryFileUpload:
			fmt.Fprintf(&buf, "\t// File upload: %s holds a path, not the contents\n", fc.FlagName)
			fmt.Fprintf(&buf, "\t%s string\n", fc.VarName)
		default:
			// Generate variable
			if fc.Field.Description != "" {
				fmt.Fprintf(&buf, "\t// %s\n", fc.Field.Description)
			}
			fmt.Fprintf(&buf, "\t%s %s\n", fc.VarName, fc.GoType)
		}
		buf.WriteString("\n")
	}

	buf.WriteString(")\n\n")

	// Generate register function
	if err := generateRegisterFunction(&buf, config); err != nil {
		return "", errors, err
	}

	// Generate build function
	if err := generateBuildFunction(&buf, config, schemas); err != nil {
		return "", errors, err
	}

	return buf.String(), errors, nil
}

func generateRegisterFunction(buf *bytes.Buffer, config *CommandConfig) error {
	fmt.Fprintf(buf, "// Register%sFlags registers all flags for %s command\n", config.Name, config.Name)
	fmt.Fprintf(buf, "func Register%sFlags(cmd *cobra.Command) {\n", config.Name)

	for _, fc := range config.Fields {
		if fc.Category == CategoryUnsupported || fc.Category == CategorySkipped {
			continue
		}

		switch fc.Category {
		case CategoryFlattenedFlags:
			// Register sub-fields
			fmt.Fprintf(buf, "\t// %s (flattened object)\n", fc.Field.Name)
			for _, subFC := range fc.SubFields {
				generateFlagRegistration(buf, subFC)
			}
		case CategoryJSONDocument:
			description := fc.Field.Description
			if description == "" {
				description = fc.FlagName
			}
			fmt.Fprintf(buf, "\tcmd.Flags().StringVar(&%s, \"%s\", \"\", %s)\n",
				fc.VarName, fc.FlagName, strconv.Quote(description+", as inline JSON, @file, or - for stdin"))
		case CategoryFileUpload:
			generateFlagRegistration(buf, fc)
			if fc.Field.Required {
				fmt.Fprintf(buf, "\t_ = cmd.MarkFlagRequired(\"%s\")\n", fc.FlagName)
			}
		default:
			generateFlagRegistration(buf, fc)
		}
	}

	buf.WriteString("}\n\n")
	return nil
}

// appendAPIDefault notes the server-side default in a flag's help text.
// Booleans benefit most: cobra shows nothing for a false default, so a flag
// whose API default is true reads as "off unless you pass this" when the
// opposite is true.
func appendAPIDefault(description string, fc *FieldConfig) string {
	if fc.Field == nil || fc.Field.Default == nil {
		return description
	}
	return fmt.Sprintf("%s (API default: %v)", strings.TrimRight(description, " "), fc.Field.Default)
}

func generateFlagRegistration(buf *bytes.Buffer, fc *FieldConfig) {
	defaultValue := getDefaultValue(fc)
	description := fc.Field.Description
	if description == "" {
		description = fc.FlagName
	}

	// Surface the API's default in the help text rather than as the registered
	// flag default. Non-boolean flags are sent on a zero-value check
	// (`if X != ""`, `if X > 0`), so registering the API default would start
	// transmitting it on every call and freeze today's server-side value into
	// the client. Showing it keeps the API authoritative while telling the user
	// what happens if they omit the flag.
	description = appendAPIDefault(description, fc)

	// Add enum values to description
	if fc.Category == CategoryEnumFlag && len(fc.Field.Enum) > 0 {
		description += fmt.Sprintf(" (%s)", strings.Join(fc.Field.Enum, ", "))
	}

	switch fc.FlagType {
	case "StringVar":
		fmt.Fprintf(buf, "\tcmd.Flags().StringVar(&%s, \"%s\", \"%s\", %s)\n",
			fc.VarName, fc.FlagName, defaultValue, strconv.Quote(description))
	case "IntVar":
		fmt.Fprintf(buf, "\tcmd.Flags().IntVar(&%s, \"%s\", %s, %s)\n",
			fc.VarName, fc.FlagName, defaultValue, strconv.Quote(description))
	case "BoolVar":
		fmt.Fprintf(buf, "\tcmd.Flags().BoolVar(&%s, \"%s\", %s, %s)\n",
			fc.VarName, fc.FlagName, defaultValue, strconv.Quote(description))
	case "Float64Var":
		fmt.Fprintf(buf, "\tcmd.Flags().Float64Var(&%s, \"%s\", %s, %s)\n",
			fc.VarName, fc.FlagName, defaultValue, strconv.Quote(description))
	case "StringSliceVar":
		fmt.Fprintf(buf, "\tcmd.Flags().StringSliceVar(&%s, \"%s\", []string{}, %s)\n",
			fc.VarName, fc.FlagName, strconv.Quote(description+" (repeatable)"))
	}
}

// getDefaultValue returns the value a flag is REGISTERED with, which is
// deliberately the Go zero value rather than the API's default.
//
// Request builders send non-boolean fields on a zero-value check
// (`if X != ""`, `if X > 0`). Registering the API default would make those
// checks always true, so every call would transmit today's server-side value
// and the API could never change its own default again. The API default is
// reported in the help text instead - see appendAPIDefault.
func getDefaultValue(fc *FieldConfig) string {
	switch fc.Field.Type {
	case "string":
		return ""
	case "integer":
		return "0"
	case "boolean":
		return "false"
	case "number":
		return "0.0"
	default:
		return ""
	}
}

func generateBuildFunction(buf *bytes.Buffer, config *CommandConfig, schemas map[string]*Field) error {
	if config.IsMultipart {
		return generateMultipartBuildFunction(buf, config)
	}
	fmt.Fprintf(buf, "// Build%sRequest builds the API request from CLI flags\n", config.Name)
	fmt.Fprintf(buf, "func Build%sRequest(cmd *cobra.Command) (*api.%s, error) {\n", config.Name, config.RequestBodyType)
	fmt.Fprintf(buf, "\tbody := &api.%s{}\n\n", config.RequestBodyType)

	for _, fc := range config.Fields {
		if fc.Category == CategoryUnsupported || fc.Category == CategorySkipped {
			continue
		}

		switch fc.Category {
		case CategorySimpleFlag:
			generateSimpleFieldMapping(buf, fc)
		case CategoryEnumFlag:
			generateEnumFieldMapping(buf, fc, config)
		case CategoryFlattenedFlags:
			generateFlattenedFieldMapping(buf, fc, config, schemas)
		case CategoryRepeatedFlag:
			generateRepeatedFieldMapping(buf, fc)
		case CategoryJSONDocument:
			generateJSONDocumentBodyMapping(buf, fc)
		case CategoryFileUpload:
			// A file part has nowhere to go on an application/json body.
			return fmt.Errorf(
				"%s: field %q needs a multipart body but %s %s is application/json",
				config.Name, fc.Field.Name, config.HTTPMethod, config.EndpointPath)
		}
	}

	buf.WriteString("\treturn body, nil\n")
	buf.WriteString("}\n")

	return nil
}

// generateMultipartBuildFunction emits a builder for a multipart/form-data
// endpoint.
//
// It returns the encoded body rather than a typed struct because oapi-codegen
// generates no multipart encoder: the only client method is
// FunctionCreateWithBody(ctx, params, contentType, io.Reader), so somebody has
// to run the writer, and doing it here is what keeps the field list tied to the
// spec.
func generateMultipartBuildFunction(buf *bytes.Buffer, config *CommandConfig) error {
	fmt.Fprintf(buf, "// Build%sBody encodes the multipart request body from CLI flags.\n", config.Name)
	fmt.Fprintf(buf, "// It returns the body and the Content-Type header describing its boundary.\n")
	fmt.Fprintf(buf, "func Build%sBody(cmd *cobra.Command) (io.Reader, string, error) {\n", config.Name)
	buf.WriteString("\tvar body bytes.Buffer\n")
	buf.WriteString("\twriter := multipart.NewWriter(&body)\n\n")

	for _, fc := range config.Fields {
		if fc.Category == CategoryUnsupported || fc.Category == CategorySkipped {
			continue
		}
		switch fc.Category {
		case CategoryFileUpload:
			generateFilePartMapping(buf, fc)
		case CategoryJSONDocument:
			generateJSONDocumentPartMapping(buf, fc)
		default:
			generateFormFieldMapping(buf, fc)
		}
	}

	buf.WriteString("\tif err := writer.Close(); err != nil {\n")
	buf.WriteString("\t\treturn nil, \"\", fmt.Errorf(\"failed to finalize request body: %w\", err)\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\treturn &body, writer.FormDataContentType(), nil\n")
	buf.WriteString("}\n")
	return nil
}

func generateFilePartMapping(buf *bytes.Buffer, fc *FieldConfig) {
	fmt.Fprintf(buf, "\t// %s (file upload)\n", fc.Field.Name)
	if fc.Field.Required {
		fmt.Fprintf(buf, "\tif %s == \"\" {\n", fc.VarName)
		fmt.Fprintf(buf, "\t\treturn nil, \"\", fmt.Errorf(\"--%s is required\")\n", fc.FlagName)
		buf.WriteString("\t}\n")
	} else {
		fmt.Fprintf(buf, "\tif %s != \"\" {\n", fc.VarName)
	}
	fmt.Fprintf(buf, "\tfile, err := os.Open(%s)\n", fc.VarName)
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, \"\", fmt.Errorf(\"failed to open file: %w\", err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tdefer func() { _ = file.Close() }()\n")
	fmt.Fprintf(buf, "\tpart, err := writer.CreateFormFile(\"%s\", filepath.Base(%s))\n", fc.Field.Name, fc.VarName)
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, \"\", fmt.Errorf(\"failed to create form file: %w\", err)\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\tif _, err := io.Copy(part, file); err != nil {\n")
	buf.WriteString("\t\treturn nil, \"\", fmt.Errorf(\"failed to copy file data: %w\", err)\n")
	buf.WriteString("\t}\n")
	if !fc.Field.Required {
		buf.WriteString("\t}\n")
	}
	buf.WriteString("\n")
}

// generateJSONDocumentBodyMapping puts a JSON document onto an application/json
// body as an object. readJSONDocumentFlag still owns the CLI input shapes
// (inline / @file / stdin); the compacted string is unmarshaled into the map
// the generated client field expects.
func generateJSONDocumentBodyMapping(buf *bytes.Buffer, fc *FieldConfig) {
	apiFieldName := toCamelCase(fc.Field.JSONName)
	if apiFieldName == "" {
		apiFieldName = toCamelCase(fc.Field.Name)
	}
	local := goLocalName(fc.Field.Name)

	fmt.Fprintf(buf, "\t// %s (JSON document)\n", fc.Field.Name)
	fmt.Fprintf(buf, "\t%s, err := readJSONDocumentFlag(cmd, \"%s\", %s)\n",
		local, fc.FlagName, fc.VarName)
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, err\n")
	buf.WriteString("\t}\n")
	fmt.Fprintf(buf, "\tif %s != \"\" {\n", local)
	buf.WriteString("\t\tvar document map[string]interface{}\n")
	fmt.Fprintf(buf, "\t\tif err := json.Unmarshal([]byte(%s), &document); err != nil {\n", local)
	fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"failed to parse --%s: %%w\", err)\n", fc.FlagName)
	buf.WriteString("\t\t}\n")
	fmt.Fprintf(buf, "\t\tbody.%s = &document\n", apiFieldName)
	buf.WriteString("\t}\n\n")
}

// generateJSONDocumentPartMapping defers to readJSONDocumentFlag, which is
// hand-written: a document can arrive inline, from @file or on stdin, and it is
// validated as JSON before it is sent because the API stores the field verbatim.
func generateJSONDocumentPartMapping(buf *bytes.Buffer, fc *FieldConfig) {
	fmt.Fprintf(buf, "\t// %s (JSON document)\n", fc.Field.Name)
	fmt.Fprintf(buf, "\t%s, err := readJSONDocumentFlag(cmd, \"%s\", %s)\n",
		goLocalName(fc.Field.Name), fc.FlagName, fc.VarName)
	buf.WriteString("\tif err != nil {\n")
	buf.WriteString("\t\treturn nil, \"\", err\n")
	buf.WriteString("\t}\n")
	fmt.Fprintf(buf, "\tif %s != \"\" {\n", goLocalName(fc.Field.Name))
	fmt.Fprintf(buf, "\t\tif err := writer.WriteField(\"%s\", %s); err != nil {\n",
		fc.Field.Name, goLocalName(fc.Field.Name))
	fmt.Fprintf(buf, "\t\t\treturn nil, \"\", fmt.Errorf(\"failed to write %s field: %%w\", err)\n", fc.Field.Name)
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")
}

// generateFormFieldMapping writes a scalar as a form field, on the same
// "only if the caller asked" rule the JSON builders use: an omitted flag must
// leave the server's default, or the previous value, alone.
func generateFormFieldMapping(buf *bytes.Buffer, fc *FieldConfig) {
	fmt.Fprintf(buf, "\t// %s\n", fc.Field.Name)
	value := fc.VarName
	condition := fmt.Sprintf("%s != \"\"", fc.VarName)
	switch fc.Field.Type {
	case "boolean":
		value = fmt.Sprintf("strconv.FormatBool(%s)", fc.VarName)
		condition = fmt.Sprintf("cmd.Flags().Changed(%q)", fc.FlagName)
	case "integer", "number":
		value = fmt.Sprintf("fmt.Sprint(%s)", fc.VarName)
		condition = fmt.Sprintf("cmd.Flags().Changed(%q)", fc.FlagName)
	}
	fmt.Fprintf(buf, "\tif %s {\n", condition)
	fmt.Fprintf(buf, "\t\tif err := writer.WriteField(\"%s\", %s); err != nil {\n", fc.Field.Name, value)
	fmt.Fprintf(buf, "\t\t\treturn nil, \"\", fmt.Errorf(\"failed to write %s field: %%w\", err)\n", fc.Field.Name)
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")
}

func generateSimpleFieldMapping(buf *bytes.Buffer, fc *FieldConfig) {
	apiFieldName := toCamelCase(fc.Field.JSONName)
	if apiFieldName == "" {
		apiFieldName = toCamelCase(fc.Field.Name)
	}

	// Required fields in API are non-pointer types, assign directly
	// Optional fields are pointer types, take address
	assignOp := "&" + fc.VarName
	if fc.Field.Required {
		assignOp = fc.VarName
	}

	if fc.Field.Type == "boolean" {
		// For booleans, check if flag was changed
		fmt.Fprintf(buf, "\tif cmd.Flags().Changed(\"%s\") {\n", fc.FlagName)
		fmt.Fprintf(buf, "\t\tbody.%s = %s\n", apiFieldName, assignOp)
		buf.WriteString("\t}\n\n")
	} else if fc.Field.Required {
		// For required fields, validate non-empty for strings
		fmt.Fprintf(buf, "\tif cmd.Flags().Changed(\"%s\") {\n", fc.FlagName)
		if fc.Field.Type == "string" {
			fmt.Fprintf(buf, "\t\tif %s == \"\" {\n", fc.VarName)
			fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"--%s cannot be empty\")\n", fc.FlagName)
			buf.WriteString("\t\t}\n")
		}
		fmt.Fprintf(buf, "\t\tbody.%s = %s\n", apiFieldName, assignOp)
		buf.WriteString("\t}\n\n")
	} else {
		// For optional fields, check if non-zero
		switch fc.Field.Type {
		case "string":
			fmt.Fprintf(buf, "\tif %s != \"\" {\n", fc.VarName)
			fmt.Fprintf(buf, "\t\tbody.%s = &%s\n", apiFieldName, fc.VarName)
			buf.WriteString("\t}\n\n")
		case "integer", "number":
			fmt.Fprintf(buf, "\tif %s > 0 {\n", fc.VarName)
			fmt.Fprintf(buf, "\t\tbody.%s = &%s\n", apiFieldName, fc.VarName)
			buf.WriteString("\t}\n\n")
		}
	}
}

func generateEnumFieldMapping(buf *bytes.Buffer, fc *FieldConfig, config *CommandConfig) {
	apiFieldName := toCamelCase(fc.Field.JSONName)
	if apiFieldName == "" {
		apiFieldName = toCamelCase(fc.Field.Name)
	}

	fmt.Fprintf(buf, "\tif %s != \"\" {\n", fc.VarName)

	if fc.Field.IsUnionType {
		// Union type (anyOf with enum + string) - use From*1 method to set string value
		unionTypeName := fmt.Sprintf("%s_%s", config.RequestBodyType, apiFieldName)
		fmt.Fprintf(buf, "\t\tvar val api.%s\n", unionTypeName)
		fmt.Fprintf(buf, "\t\tif err := val.From%s%s1(%s); err != nil {\n",
			config.RequestBodyType, apiFieldName, fc.VarName)
		fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"invalid %s: %%w\", err)\n", fc.FlagName)
		buf.WriteString("\t\t}\n")
		fmt.Fprintf(buf, "\t\tbody.%s = &val\n", apiFieldName)
	} else {
		// Simple enum type - direct cast
		enumTypeName := fmt.Sprintf("%s%s", config.RequestBodyType, apiFieldName)
		fmt.Fprintf(buf, "\t\tval := api.%s(%s)\n", enumTypeName, fc.VarName)
		fmt.Fprintf(buf, "\t\tbody.%s = &val\n", apiFieldName)
	}

	buf.WriteString("\t}\n\n")
}

func generateFlattenedFieldMapping(buf *bytes.Buffer, fc *FieldConfig, config *CommandConfig, schemas map[string]*Field) {
	apiFieldName := toCamelCase(fc.Field.JSONName)
	if apiFieldName == "" {
		apiFieldName = toCamelCase(fc.Field.Name)
	}

	// Resolve the struct type (convert to valid Go identifier by removing hyphens)
	structTypeName := fc.Field.Ref
	if structTypeName == "" {
		structTypeName = apiFieldName
	}
	// Convert hyphenated names to CamelCase (e.g., "CredentialsDict-Input" -> "CredentialsDictInput")
	structTypeName = strings.ReplaceAll(structTypeName, "-", "")

	// Build conditions for required and optional fields
	var requiredConditions []string
	var optionalConditions []string
	for _, subFC := range fc.SubFields {
		if subFC.Field.Required && subFC.Field.Type == "string" {
			requiredConditions = append(requiredConditions, fmt.Sprintf("%s != \"\"", subFC.VarName))
		} else if subFC.Field.Type == "string" {
			optionalConditions = append(optionalConditions, fmt.Sprintf("%s != \"\"", subFC.VarName))
		} else {
			optionalConditions = append(optionalConditions, fmt.Sprintf("cmd.Flags().Changed(\"%s\")", subFC.FlagName))
		}
	}

	// If there are required fields, validate they're provided when optional fields are set
	var condition string
	if len(requiredConditions) > 0 {
		condition = strings.Join(requiredConditions, " && ")
		// Add validation: error if optional fields set without required fields
		if len(optionalConditions) > 0 {
			// Collect required flag names for error message
			var requiredFlagNames []string
			for _, subFC := range fc.SubFields {
				if subFC.Field.Required && subFC.Field.Type == "string" {
					requiredFlagNames = append(requiredFlagNames, "--"+subFC.FlagName)
				}
			}
			optionalCond := strings.Join(optionalConditions, " || ")
			fmt.Fprintf(buf, "\t// %s: validate required fields when optional fields are provided\n", fc.Field.Name)
			fmt.Fprintf(buf, "\tif (%s) && !(%s) {\n", optionalCond, condition)
			fmt.Fprintf(buf, "\t\treturn nil, fmt.Errorf(\"%s requires %s to be set\")\n",
				fc.FlagName, strings.Join(requiredFlagNames, ", "))
			buf.WriteString("\t}\n\n")
		}
	} else {
		// No required fields - use OR for any field being set
		condition = strings.Join(optionalConditions, " || ")
	}

	fmt.Fprintf(buf, "\t// %s (flattened) - only set if required fields are provided\n", fc.Field.Name)
	fmt.Fprintf(buf, "\tif %s {\n", condition)

	// Separate required and optional subfields
	var requiredSubFields, optionalSubFields []*FieldConfig
	for _, subFC := range fc.SubFields {
		if subFC.Field.Required {
			requiredSubFields = append(requiredSubFields, subFC)
		} else {
			optionalSubFields = append(optionalSubFields, subFC)
		}
	}

	// If no optional fields, use struct literal directly
	if len(optionalSubFields) == 0 {
		if fc.Field.Required {
			fmt.Fprintf(buf, "\t\tbody.%s = api.%s{\n", apiFieldName, structTypeName)
		} else {
			fmt.Fprintf(buf, "\t\tbody.%s = &api.%s{\n", apiFieldName, structTypeName)
		}
		for _, subFC := range requiredSubFields {
			subAPIFieldName := toCamelCase(subFC.Field.JSONName)
			if subAPIFieldName == "" {
				subAPIFieldName = toCamelCase(subFC.Field.Name)
			}
			fmt.Fprintf(buf, "\t\t\t%s: %s,\n", subAPIFieldName, subFC.VarName)
		}
		buf.WriteString("\t\t}\n")
	} else {
		// Create struct and conditionally set optional fields
		varName := strings.ToLower(string(apiFieldName[0])) + apiFieldName[1:]
		fmt.Fprintf(buf, "\t\t%s := api.%s{\n", varName, structTypeName)
		for _, subFC := range requiredSubFields {
			subAPIFieldName := toCamelCase(subFC.Field.JSONName)
			if subAPIFieldName == "" {
				subAPIFieldName = toCamelCase(subFC.Field.Name)
			}
			fmt.Fprintf(buf, "\t\t\t%s: %s,\n", subAPIFieldName, subFC.VarName)
		}
		buf.WriteString("\t\t}\n")

		// Conditionally set optional fields only when non-empty
		for _, subFC := range optionalSubFields {
			subAPIFieldName := toCamelCase(subFC.Field.JSONName)
			if subAPIFieldName == "" {
				subAPIFieldName = toCamelCase(subFC.Field.Name)
			}
			if subFC.Field.Type == "string" {
				fmt.Fprintf(buf, "\t\tif %s != \"\" {\n", subFC.VarName)
				fmt.Fprintf(buf, "\t\t\t%s.%s = &%s\n", varName, subAPIFieldName, subFC.VarName)
				buf.WriteString("\t\t}\n")
			} else {
				fmt.Fprintf(buf, "\t\tif cmd.Flags().Changed(\"%s\") {\n", subFC.FlagName)
				fmt.Fprintf(buf, "\t\t\t%s.%s = &%s\n", varName, subAPIFieldName, subFC.VarName)
				buf.WriteString("\t\t}\n")
			}
		}

		// Assign to body
		if fc.Field.Required {
			fmt.Fprintf(buf, "\t\tbody.%s = %s\n", apiFieldName, varName)
		} else {
			fmt.Fprintf(buf, "\t\tbody.%s = &%s\n", apiFieldName, varName)
		}
	}

	buf.WriteString("\t}\n\n")
}

func generateRepeatedFieldMapping(buf *bytes.Buffer, fc *FieldConfig) {
	apiFieldName := toCamelCase(fc.Field.JSONName)
	if apiFieldName == "" {
		apiFieldName = toCamelCase(fc.Field.Name)
	}

	fmt.Fprintf(buf, "\tif len(%s) > 0 {\n", fc.VarName)
	// Pass the slice directly as a pointer - API expects *[]string or similar
	fmt.Fprintf(buf, "\t\tbody.%s = &%s\n", apiFieldName, fc.VarName)

	buf.WriteString("\t}\n\n")
}
